spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_timesheet
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwtAdmin:
  secret: "ADMIN_GROUP"

jwtSecretKey:
  secret: "SECRET_KEY"

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
